version: '3'
services:
  avito:
    image: postgres:14
    container_name: avito
    hostname: avito
    restart: unless-stopped
    networks:
      - avito_net
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=avito

  web:
    build: .
    networks:
      - avito_net
    ports: 
      - "3000:3000"
    depends_on:
      - avito

networks:
  avito_net:
    driver: bridge